[files]
extend-exclude = ["*.bin"]

[default]
extend-ignore-identifiers-re = ["arange"]

[default.extend-identifiers]
check_arange = "check_arange"
dout = "dout"
Hel = "Hel"
test_arange = "test_arange"
