site_name: compression-safeguards

strict: true

markdown_extensions:
  - footnotes
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

theme:
  name: readthedocs
  highlightjs: false
  navigation_depth: 99

nav:
  - Home: index.md
  - Links:
      - GitHub: https://github.com/juntyr/compression-safeguards
      - PyPI:
        - compression-safeguards: https://pypi.org/project/compression-safeguards/
        - numcodecs-safeguards: https://pypi.org/project/numcodecs-safeguards/

plugins:
  - exclude:
      glob:
        - requirements.txt
  - search
  - open-in-new-tab
  - autorefs
  - mkdocstrings-python-generator:
      source_dirs:
        - nav_heading: [API Reference]
          base: src
          ignore: ["_qois"]
        - nav_heading: [API Reference]
          base: packages/numcodecs-safeguards/src
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_section_style: list
            docstring_style: numpy
            show_if_no_docstring: true
            filters: ["!^_$", "!^_[^_]", "!^__", "__init__"]
            members_order: source
            group_by_category: false
            show_source: false
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_root_toc_entry: false
            merge_init_into_class: true
            summary:
              attributes: false
              classes: true
              functions: true
              modules: true
          inventories:
            - https://docs.python.org/3.12/objects.inv
            - https://numpy.org/doc/2.2/objects.inv
            - https://numcodecs.readthedocs.io/en/v0.15.0/objects.inv
            - https://numcodecs-combinators.readthedocs.io/en/v0.2.7/objects.inv
            - https://numcodecs-zero.readthedocs.io/en/v0.1.0/objects.inv

watch:
  - src
  - packages
