[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "numcodecs-safeguards"
version = "0.1.0"
description = "Fearless lossy compression using safeguards"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "compression-safeguards~=1.0",
    "numcodecs>=0.13.0,<0.17",
    "numcodecs-combinators~=0.2.10",
    "numcodecs-delta~=0.1.0",
    "numcodecs-huffman~=0.1.0",
    "numcodecs-zero~=0.1.0",
    "numpy~=2.0",
    "semver~=3.0",
    "typing-extensions~=4.6",
    "varint~=1.0",
]

[project.entry-points."numcodecs.codecs"]
"safeguards" = "numcodecs_safeguards:SafeguardsCodec"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"numcodecs_safeguards" = ["py.typed"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "NPY", "T20", "SLOT", "TC", "PLC", "UP", "FURB"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
xfail_strict = true

[[tool.mypy.overrides]]
module = [
    "numcodecs.*",
    "varint.*",
]
follow_untyped_imports = true

[tool.hatch.build.targets.sdist]
include = ["/src", "/CITATION.cff", "/LICENSE", "/pyproject.toml", "/README.md"]

[tool.uv.sources]
compression-safeguards = { workspace = true }
