name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  CLICOLOR: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Check with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check

  spelling:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4

    - name: Spellcheck repo
      uses: crate-ci/typos@v1.32.0

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Check with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --diff --check"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install

      - name: Install numcodecs-safeguards
        run: uv sync --only-group test && uv pip install .

      - name: Run tests
        run: uv run pytest -v -W error

  mypy:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install

      - name: Install numcodecs-safeguards
        run: uv sync --only-group typing && uv pip install .

      - name: Install numpy-quaddtype
        run: uv pip install -i https://test.pypi.org/simple/ numpy-quaddtype~=0.0.7

      - name: Typecheck numcodecs-safeguards
        run: uv run mypy -p numcodecs_safeguards

  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install

      - name: Install numcodecs-safeguards
        run: uv sync --only-group fuzz && uv pip install .

      - name: Restore the fuzzer corpus
        id: fuzzer-corpus-restore
        uses: actions/cache/restore@v4
        with:
          path: ./corpus
          key: fuzzer-corpus

      - name: Ensure the fuzzer corpus exists
        run: |
          mkdir -p ./corpus/safeguards
          mkdir -p ./corpus/intervals

      - name: Run the fuzzers
        run: |
          uv run fuzz/fuzz_safeguards.py ./corpus/safeguards -max_total_time=45
          uv run fuzz/fuzz_safeguards.py ./corpus/intervals -max_total_time=15

      - name: Delete the previous fuzzer corpus
        if: always() && steps.fuzzer-corpus-restore.outputs.cache-hit == 'true'
        run: gh cache delete fuzzer-corpus
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save the fuzzer corpus
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ./corpus
          key: fuzzer-corpus
