name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  CLICOLOR: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Check with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check

  spelling:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Spellcheck repo
        uses: crate-ci/typos@v1.32.0

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Check with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --diff --check"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup the Python venv with the safeguards
        run: uv sync --all-packages --group test

      - name: Run tests
        run: uv run pytest -v -W error

  mypy:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup the Python venv with the safeguards
        run: uv sync --all-packages --group typing

      - name: Typecheck compression-safeguards
        run: uv run mypy -p compression_safeguards

      - name: Typecheck numcodecs-safeguards
        run: cd packages/numcodecs-safeguards && uv run mypy -p numcodecs_safeguards

      - name: Typecheck xarray-safeguards
        run: cd packages/xarray-safeguards && uv run mypy -p xarray_safeguards

  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup the Python venv with the safeguards
        run: uv sync --all-packages --group fuzz

      - name: Restore the fuzzer corpus
        id: fuzzer-corpus-restore
        uses: actions/cache/restore@v4
        with:
          path: ./corpus
          key: fuzzer-corpus

      - name: Ensure the fuzzer corpus exists
        run: |
          mkdir -p ./corpus/safeguards
          mkdir -p ./corpus/intervals
          mkdir -p ./corpus/qois
          mkdir -p ./corpus/chunking

      - name: Run the fuzzers
        run: |
          uv run fuzz/fuzz_safeguards.py ./corpus/safeguards -max_total_time=60
          uv run fuzz/fuzz_intervals.py ./corpus/intervals -max_total_time=30
          uv run fuzz/fuzz_qois.py ./corpus/qois -max_total_time=60
          uv run fuzz/fuzz_chunking.py ./corpus/chunking -max_total_time=30

      - name: Delete the previous fuzzer corpus
        if: always() && steps.fuzzer-corpus-restore.outputs.cache-hit == 'true'
        run: gh cache delete fuzzer-corpus
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save the fuzzer corpus
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ./corpus
          key: fuzzer-corpus

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup the Python venv with the safeguards
        run: uv sync --all-packages

      - name: Install mkdocs dependencies
        run: uv pip install -r docs/requirements.txt

      # https://github.com/mkdocstrings/python/issues/167
      - name: Reduce docs duplication
        run: sed -i 's/__all__ = \["Safeguards", "SafeguardKind"\]/__all__ = \[\]/g' src/compression_safeguards/__init__.py

      - name: Check docs build
        run: uv run mkdocs build

  doctest:
    name: Doctest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup the Python venv with the safeguards
        run: uv sync --all-packages --group doctest

      - name: Compile all docs
        run: |
          cp README.md docs/
          uv run griffe2md src/compression_safeguards/ -o docs/compression_safeguards.md
          uv run griffe2md packages/numcodecs-safeguards/src/numcodecs_safeguards/ -o docs/numcodecs_safeguards.md
          uv run griffe2md packages/xarray-safeguards/src/xarray_safeguards/ -o docs/xarray_safeguards.md
          find docs -type f -name "*.md" | xargs sed -i -e 's/```py/```python/g'

      - name: Run doctests
        run: uv run pytest -v -W error --codeblocks docs/
