name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Check with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Check with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --diff --check"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install

      - name: Install numcodecs-guardrails
        run: uv sync --only-group test && uv pip install .

      - name: Run tests
        run: uv run pytest

  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      
      - name: Fake compatibility with Python 3.11
        run: |
          sed -i 's/requires-python = ">=3.12"/requires-python = ">=3.11"/g' pyproject.toml
          find . -type f -name "*.py" -print0 | xargs -0 sed -i 's/from collections.abc import Buffer/from typing import Any as Buffer/g'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install 3.11

      - name: Install numcodecs-guardrails
        run: uv sync --only-group fuzz && uv pip install .

      - name: Restore the fuzzer corpus
        id: fuzzer-corpus-restore
        uses: actions/cache/restore@v4
        with:
          path: ./corpus
          key: fuzzer-corpus

      - name: Ensure the fuzzer corpus exists
        run: mkdir -p ./corpus

      - name: Run the fuzzer
        run: uv run tests/fuzz.py ./corpus -max_total_time=60

      - name: Delete the previous fuzzer corpus
        if: always() && steps.fuzzer-corpus-restore.outputs.cache-hit == 'true'
        run: gh cache delete fuzzer-corpus
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save the fuzzer corpus
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ./corpus
          key: fuzzer-corpus
